export const ActionTypes = {
  SET_CHARACTERS: "SET_CHARACTERS",
  SELECTED_CHARACTER: "SELECTED_CHARACTER",
  SEARCH_CHARACTERS: "SEARCH_CHARACTERS",
  REMOVE_SELECTED_CHARACTER: "REMOVE_SELECTED_CHARACTER",
};
