export const SET_DARK_MODE = "SET_DARK_MODE";
export const GET_CHARACTER_LIST_LOADING = "GET_CHARACTER_LIST_LOADING";
export const GET_CHARACTER_LIST_SUCCESS = "GET_CHARACTER_LIST_SUCCESS";
export const GET_CHARACTER_LIST_ERROR = "GET_CHARACTER_LIST_ERROR";
export const GET_CHARACTER_LOADING = "GET_CHARACTER_LOADING";
export const GET_CHARACTER_SUCCESS = "GET_CHARACTER_SUCCESS";
export const GET_CHARACTER_ERROR = "GET_CHARACTER_ERROR";
