export const GET_ALLCHARACTERS = "GET_ALLCHARACTERS"
export const GET_ALLCHARACTERS_SUCCESS = "GET_ALLCHARACTERS_SUCCESS"
export const GET_ALLCHARACTERS_ERROR = "GET_ALLCHARACTERS_ERROR"

export const GET_SIGLE_CHARACTER = "GET_SIGLE_CHARACTER"
export const GET_SINGLE_CHARACTER_SUCCESS = "GET_SINGLE_CHARACTER_SUCCESS"
export const GET_SINGLE_CHARACTER_ERROR = "GET_SINGLE_CHARACTER_ERROR"

export const SEARCH_CARACTER = "SEARCH_CARACTER"
export const SEARCH_CHARACTER_SUCCESS = "SEARCH_CHARACTER_SUCCESS"
export const SEARCH_CHARACTER_ERROR = "SEARCH_CHARACTER_ERROR"

export const GET_PAGINATION = "GET_PAGINATION"
export const GET_PAGINATION_SUCCESS = "GET_PAGINATION_SUCCESS"
export const GET_PAGINATION_ERROR = "GET_PAGINATION_ERROR"
